controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

add_comment:
    path: /add-comment
    controller: 'App\Controller\HomeController::addComment'
    methods: ['POST']