controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

add_comment:
    path: /add-comment
    controller: 'App\Controller\TrickController::addComment'
    methods: ['POST']

showMoreTricks:
    path: /show-more-tricks
    controller: 'App\Controller\HomeController::showMoreTricks'
    methods: [ 'GET' ]